name: Feature Request
description: Suggest a new feature or enhancement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or problem you're trying to solve
      placeholder: I need to be able to... because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: The plugin could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative solutions you've thought about?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information or examples
